plugins:
  - jekyll-redirect-from

collections:
  members:
    output: true
    permalink: /ja/member/:slug

defaults:
  -
    scope:
      path: "en"
    values:
      lang: "en"
      linked_page: "/ja/"

  -
    scope:
      path: "ja"
    values:
      lang: "ja"
      linked_page: "/en/"

  -
    scope:
      path: ""
      type: "members"
    values:
      layout: "member"
      lang: "ja"
      linked_page: "/en/"
