plugins:
  - jekyll-redirect-from

collections:
  pages_en:
    output: true
    permalink: /en/:name
    sort_by: order
  
  pages_ja:
    output: true
    permalink: /ja/:name
    sort_by: order

defaults:
  -
    scope:
      path: ""
      type: "pages_en"
    values:
      layout: "default"
      lang: "en"
      linked_page: "/ja/"

  -
    scope:
      path: ""
      type: "pages_ja"
    values:
      layout: "default"
      lang: "ja"
      linked_page: "/en/"
