plugins:
  - jekyll-redirect-from

collections:
  pages_en:
    output: true
    permalink: /en/:name
  
  pages_ja:
    output: true
    permalink: /ja/:name

  members:
    output: true
    permalink: /ja/member/:slug

defaults:
  -
    scope:
      path: ""
      type: "pages_en"
    values:
      layout: "page"
      lang: "en"
      linked_page: "/ja/"

  -
    scope:
      path: ""
      type: "pages_ja"
    values:
      layout: "page"
      lang: "ja"
      linked_page: "/en/"

  -
    scope:
      path: ""
      type: "members"
    values:
      layout: "member"
      lang: "ja"
      linked_page: "/en/"
